language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-html --href-ignore github.com,/\/blob.*/ --checks-to-ignore ScriptCheck,ImageCheck
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
